### ISSUE TITLE
School project in need of tips & tricks

### ISSUE THREAD

**Issue by BackendBob** [BackendBob/PingPong#2]
Just for fun. Making a project with web development class. Pitch in if you'd like, or give some pointers on how to make the most out of this! :)

**Comment by Shaun2D2** [comment]
Hey @Niklasson89 ,

wondering how you would feel about configuring this application to support composer, and in turn add in things like dotenv support for database configuration.

Just looking to have some fun :)

Shaun

**Comment by Niklasson89** [comment]
Hi @Shaun2D2 ! Honestly, I'm not at all familiar with composer, and it's unclear whether my contributors are either. We've only been studying web dev. for 7 weeks or so. Will definitely check it out though, and try to read up on it. Thanks for sharing your thoughts with us! :)

**Comment by CodeBarbarian** [comment]
This looks like fun. I could do some pull requests to this later when I am off work.

**Comment by Niklasson89** [comment]
@CodeBarbarian Hey! You're welcome to help out :) Would appreciate it if you'd try to keep it around the same level as it is in its current form, since most of us are total noobs ;D

**Comment by CodeBarbarian** [comment]
@Niklasson89 No worries. Code looks great for only been studying web development for seven weeks! :+1:
